# Generated by Django 3.2.8 on 2021-10-23 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purchase', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Men', 'M'), ('Ladies', 'L'), ('Children', 'C'), ('Youth', 'Y'), ('Wasawa', 'W'), ('Ladies&Chidren', 'L and C'), ('Ladies&Wasawa', 'L and W'), ('Ladies&Men', 'L and M'), ('Youth&Wasawa', 'Y and W'), ('Children&Wasawa', 'C and W'), ('Children&Youth', 'C and Y')], max_length=30)),
                ('done', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attas.container')),
            ],
        ),
    ]
