# Generated by Django 3.2.8 on 2021-10-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('name',), 'verbose_name_plural': 'containers'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name_plural': 'customers'},
        ),
    ]
