# Generated by Django 3.2.8 on 2021-10-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attas', '0002_auto_20211023_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('-date',), 'verbose_name_plural': 'containers'},
        ),
    ]
